// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exqxrcrrfozqugukpaee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4cXhyY3JyZm96cXVndWtwYWVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2ODU1MTcsImV4cCI6MjA1NDI2MTUxN30._muGMEQDe4Gs7ysBJif9vycm9mxu1XhAKsuZuIl9mSA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);